package dev.turboism.mapping.verification;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TextureAtlasVerificationManifestTest {

    @Test
    void admitsOnlyTheCompleteExact5303CompoundLane() {
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HOOK_CANDIDATE",
            "5303",
            "texture-atlas-hook-5303",
            "run-1"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_AUTO_LAYOUT_CALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-auto-layout-callback-5303",
            "run-2"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_NATIVE_FALLBACK_COMPLETION_CANDIDATE",
            "5303",
            "texture-atlas-native-fallback-completion-5303",
            "run-3"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_THROWABLE_FALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-throwable-fallback-5303",
            "run-4"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HANDLED_TRUE_CANDIDATE",
            "5303",
            "texture-atlas-handled-true-5303",
            "run-5"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_UI_LIFECYCLE_CANDIDATE",
            "5303",
            "texture-atlas-ui-lifecycle-5303",
            "run-6"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-persist-write-5303",
            "run-7"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-persist-reopen-5303",
            "run-8"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-persist-final-5303",
            "run-9"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_UI_LIFECYCLE_CANDIDATE",
            "5303",
            "texture-atlas-handled-true-5303",
            "run-6"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-ui-lifecycle-5303",
            "run-7"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_UI_LIFECYCLE_CANDIDATE",
            "5303",
            "texture-atlas-persist-write-5303",
            "run-7"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HANDLED_TRUE_CANDIDATE",
            "5303",
            "texture-atlas-ui-lifecycle-5303",
            "run-6"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303HandledValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HANDLED_TRUE_CANDIDATE",
            "5303",
            "texture-atlas-handled-true-5303",
            "run-5"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303HandledValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_THROWABLE_FALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-handled-true-5303",
            "run-5"
        ));
        assertTrue(TextureAtlasVerificationManifest.admits5303PersistenceValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-persist-write-5303",
            "run-7"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303PersistenceValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HANDLED_TRUE_CANDIDATE",
            "5303",
            "texture-atlas-persist-write-5303",
            "run-7"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_AUTO_LAYOUT_CALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-hook-5303",
            "run-2"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HOOK_CANDIDATE",
            "5303",
            "texture-atlas-auto-layout-callback-5303",
            "run-2"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_NATIVE_FALLBACK_COMPLETION_CANDIDATE",
            "5303",
            "texture-atlas-auto-layout-callback-5303",
            "run-3"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_AUTO_LAYOUT_CALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-native-fallback-completion-5303",
            "run-3"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_THROWABLE_FALLBACK_CANDIDATE",
            "5303",
            "texture-atlas-native-fallback-completion-5303",
            "run-4"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_NATIVE_FALLBACK_COMPLETION_CANDIDATE",
            "5303",
            "texture-atlas-throwable-fallback-5303",
            "run-4"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HOOK_CANDIDATE",
            "5302",
            "texture-atlas-hook-5303",
            "run-1"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "wrong",
            "5303",
            "texture-atlas-hook-5303",
            "run-1"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HOOK_CANDIDATE",
            "5303",
            "wrong",
            "run-1"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_HOOK_CANDIDATE",
            "5303",
            "texture-atlas-hook-5303",
            " "
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5302",
            "texture-atlas-persist-write-5303",
            "run-7"
        ));
        assertFalse(TextureAtlasVerificationManifest.admits5303ValidationCandidate(
            "EXACT_5303_TEXTURE_ATLAS_PERSISTENCE_CANDIDATE",
            "5303",
            "texture-atlas-persist-write-5303",
            " "
        ));
    }
}
