rootProject.name = "turboism-root"

include(
    "bootstrap",
    "runtime",
    "sdk",
    "plugins:demo",
    "plugins:ui-theme",
    "plugins:log-filter",
    "plugins:cubism-tab-filter",
    "plugins:core",
    "plugins:perf-opt",
    "plugins:render-opt",
    "plugins:clip-mask",
    "plugins:parameter",
    "plugins:mesh",
    "plugins:mcp",
    "plugins:project-inspector",
    "plugins:bounding-box",
    "plugins:context-menu",
    "plugins:project-panel",
    "plugins:scene-palette-enhancer",
    "plugins:psd-import",
    "plugins:atlas-maxrects-bssf",
    "plugins:texture-atlas-stats",
    "plugins:physics-editor",
    "testframework",
    "tests"
)
