package dev.turboism.mapping.verification.selector;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Generated candidate registry for compatibility probing of unreviewed Cubism hosts.
 *
 * <p>Every candidate pins the SHA-256 of its reviewed verification record so a
 * tampered embedded resource can never widen the reflection surface a host is
 * probed with. Candidate data is produced from the reviewed records under
 * {@code compatibility/cubism/verification/}; do not edit this file directly -
 * edit the authoring template and rerun the verification-source generator.</p>
 *
 * <p>Candidate order inside one slice is ascending reviewed version; the
 * resolver re-orders probes toward the declared host identity. Slices that
 * share host object graphs are grouped ({@link #groupOf}) so a host can never
 * bind mixed reviewed generations inside one group.</p>
 */
public final class CubismSliceCatalog {

    /**
     * One reviewed contract candidate for one adapter slice.
     *
     * @param sliceId stable slice key such as {@code "editor-model"}
     * @param cubismVersion reviewed Cubism version the record was authored against
     * @param recordFileName embedded record resource under
     *     {@code META-INF/turboism/verification/}
     * @param recordSha256 pinned SHA-256 of that record's bytes
     * @param verificationId the record's stable verification identity
     * @param adapterSliceId the record's adapter-slice identity
     * @param profileId the record's mapping profile identity
     */
    public record Candidate(
        String sliceId,
        String cubismVersion,
        String recordFileName,
        String recordSha256,
        String verificationId,
        String adapterSliceId,
        String profileId
    ) {
        public Candidate {
            Objects.requireNonNull(sliceId, "sliceId");
            Objects.requireNonNull(cubismVersion, "cubismVersion");
            Objects.requireNonNull(recordFileName, "recordFileName");
            Objects.requireNonNull(recordSha256, "recordSha256");
            Objects.requireNonNull(verificationId, "verificationId");
            Objects.requireNonNull(adapterSliceId, "adapterSliceId");
            Objects.requireNonNull(profileId, "profileId");
        }
    }

    private static final Candidate C_AUTOBACKUP_5_2_03 = new Candidate(
        "autobackup",
        "${record:cubism-5.2.03-autobackup.json:cubismVersion}",
        "cubism-5.2.03-autobackup.json",
        "${record:cubism-5.2.03-autobackup.json:sha256}",
        "${record:cubism-5.2.03-autobackup.json:verificationId}",
        "${record:cubism-5.2.03-autobackup.json:adapterSliceId}",
        "${record:cubism-5.2.03-autobackup.json:profileId}"
    );
    private static final Candidate C_AUTOBACKUP_5_3_02 = new Candidate(
        "autobackup",
        "${record:cubism-5.3.02-autobackup.json:cubismVersion}",
        "cubism-5.3.02-autobackup.json",
        "${record:cubism-5.3.02-autobackup.json:sha256}",
        "${record:cubism-5.3.02-autobackup.json:verificationId}",
        "${record:cubism-5.3.02-autobackup.json:adapterSliceId}",
        "${record:cubism-5.3.02-autobackup.json:profileId}"
    );
    private static final Candidate C_AUTOBACKUP_5_3_03 = new Candidate(
        "autobackup",
        "${record:cubism-5.3.03-autobackup.json:cubismVersion}",
        "cubism-5.3.03-autobackup.json",
        "${record:cubism-5.3.03-autobackup.json:sha256}",
        "${record:cubism-5.3.03-autobackup.json:verificationId}",
        "${record:cubism-5.3.03-autobackup.json:adapterSliceId}",
        "${record:cubism-5.3.03-autobackup.json:profileId}"
    );
    private static final Candidate C_CLIPMASK_5_2_03 = new Candidate(
        "clipmask",
        "${record:cubism-5.2.03-clipmask.json:cubismVersion}",
        "cubism-5.2.03-clipmask.json",
        "${record:cubism-5.2.03-clipmask.json:sha256}",
        "${record:cubism-5.2.03-clipmask.json:verificationId}",
        "${record:cubism-5.2.03-clipmask.json:adapterSliceId}",
        "${record:cubism-5.2.03-clipmask.json:profileId}"
    );
    private static final Candidate C_CLIPMASK_5_3_02 = new Candidate(
        "clipmask",
        "${record:cubism-5.3.02-clipmask.json:cubismVersion}",
        "cubism-5.3.02-clipmask.json",
        "${record:cubism-5.3.02-clipmask.json:sha256}",
        "${record:cubism-5.3.02-clipmask.json:verificationId}",
        "${record:cubism-5.3.02-clipmask.json:adapterSliceId}",
        "${record:cubism-5.3.02-clipmask.json:profileId}"
    );
    private static final Candidate C_CLIPMASK_5_3_03 = new Candidate(
        "clipmask",
        "${record:cubism-5.3.03-clipmask.json:cubismVersion}",
        "cubism-5.3.03-clipmask.json",
        "${record:cubism-5.3.03-clipmask.json:sha256}",
        "${record:cubism-5.3.03-clipmask.json:verificationId}",
        "${record:cubism-5.3.03-clipmask.json:adapterSliceId}",
        "${record:cubism-5.3.03-clipmask.json:profileId}"
    );
    private static final Candidate C_CORE_MODEL_READ_5_2_03 = new Candidate(
        "core-model-read",
        "${record:cubism-5.2.03-core-model-read.json:cubismVersion}",
        "cubism-5.2.03-core-model-read.json",
        "${record:cubism-5.2.03-core-model-read.json:sha256}",
        "${record:cubism-5.2.03-core-model-read.json:verificationId}",
        "${record:cubism-5.2.03-core-model-read.json:adapterSliceId}",
        "${record:cubism-5.2.03-core-model-read.json:profileId}"
    );
    private static final Candidate C_CORE_MODEL_READ_5_3_02 = new Candidate(
        "core-model-read",
        "${record:cubism-5.3.02-core-model-read.json:cubismVersion}",
        "cubism-5.3.02-core-model-read.json",
        "${record:cubism-5.3.02-core-model-read.json:sha256}",
        "${record:cubism-5.3.02-core-model-read.json:verificationId}",
        "${record:cubism-5.3.02-core-model-read.json:adapterSliceId}",
        "${record:cubism-5.3.02-core-model-read.json:profileId}"
    );
    private static final Candidate C_EDITOR_MODEL_5_2_03 = new Candidate(
        "editor-model",
        "${record:cubism-5.2.03-editor-model.json:cubismVersion}",
        "cubism-5.2.03-editor-model.json",
        "${record:cubism-5.2.03-editor-model.json:sha256}",
        "${record:cubism-5.2.03-editor-model.json:verificationId}",
        "${record:cubism-5.2.03-editor-model.json:adapterSliceId}",
        "${record:cubism-5.2.03-editor-model.json:profileId}"
    );
    private static final Candidate C_EDITOR_MODEL_5_3_02 = new Candidate(
        "editor-model",
        "${record:cubism-5.3.02-editor-model.json:cubismVersion}",
        "cubism-5.3.02-editor-model.json",
        "${record:cubism-5.3.02-editor-model.json:sha256}",
        "${record:cubism-5.3.02-editor-model.json:verificationId}",
        "${record:cubism-5.3.02-editor-model.json:adapterSliceId}",
        "${record:cubism-5.3.02-editor-model.json:profileId}"
    );
    private static final Candidate C_EDITOR_MODEL_5_3_03 = new Candidate(
        "editor-model",
        "${record:cubism-5.3.03-editor-model.json:cubismVersion}",
        "cubism-5.3.03-editor-model.json",
        "${record:cubism-5.3.03-editor-model.json:sha256}",
        "${record:cubism-5.3.03-editor-model.json:verificationId}",
        "${record:cubism-5.3.03-editor-model.json:adapterSliceId}",
        "${record:cubism-5.3.03-editor-model.json:profileId}"
    );
    private static final Candidate C_PERFORMANCE_RENDER_SCENE_5_2_03 = new Candidate(
        "performance-render-scene",
        "${record:cubism-5.2.03-performance-render-scene.json:cubismVersion}",
        "cubism-5.2.03-performance-render-scene.json",
        "${record:cubism-5.2.03-performance-render-scene.json:sha256}",
        "${record:cubism-5.2.03-performance-render-scene.json:verificationId}",
        "${record:cubism-5.2.03-performance-render-scene.json:adapterSliceId}",
        "${record:cubism-5.2.03-performance-render-scene.json:profileId}"
    );
    private static final Candidate C_PERFORMANCE_RENDER_SCENE_5_3_02 = new Candidate(
        "performance-render-scene",
        "${record:cubism-5.3.02-performance-render-scene.json:cubismVersion}",
        "cubism-5.3.02-performance-render-scene.json",
        "${record:cubism-5.3.02-performance-render-scene.json:sha256}",
        "${record:cubism-5.3.02-performance-render-scene.json:verificationId}",
        "${record:cubism-5.3.02-performance-render-scene.json:adapterSliceId}",
        "${record:cubism-5.3.02-performance-render-scene.json:profileId}"
    );
    private static final Candidate C_PERFORMANCE_RENDER_SCENE_5_3_03 = new Candidate(
        "performance-render-scene",
        "${record:cubism-5.3.03-performance-render-scene.json:cubismVersion}",
        "cubism-5.3.03-performance-render-scene.json",
        "${record:cubism-5.3.03-performance-render-scene.json:sha256}",
        "${record:cubism-5.3.03-performance-render-scene.json:verificationId}",
        "${record:cubism-5.3.03-performance-render-scene.json:adapterSliceId}",
        "${record:cubism-5.3.03-performance-render-scene.json:profileId}"
    );
    private static final Candidate C_PROJECT_WORKSPACE_5_2_03 = new Candidate(
        "project-workspace",
        "${record:cubism-5.2.03-project-workspace.json:cubismVersion}",
        "cubism-5.2.03-project-workspace.json",
        "${record:cubism-5.2.03-project-workspace.json:sha256}",
        "${record:cubism-5.2.03-project-workspace.json:verificationId}",
        "${record:cubism-5.2.03-project-workspace.json:adapterSliceId}",
        "${record:cubism-5.2.03-project-workspace.json:profileId}"
    );
    private static final Candidate C_PROJECT_WORKSPACE_5_3_02 = new Candidate(
        "project-workspace",
        "${record:cubism-5.3.02-project-workspace.json:cubismVersion}",
        "cubism-5.3.02-project-workspace.json",
        "${record:cubism-5.3.02-project-workspace.json:sha256}",
        "${record:cubism-5.3.02-project-workspace.json:verificationId}",
        "${record:cubism-5.3.02-project-workspace.json:adapterSliceId}",
        "${record:cubism-5.3.02-project-workspace.json:profileId}"
    );
    private static final Candidate C_PROJECT_WORKSPACE_5_3_03 = new Candidate(
        "project-workspace",
        "${record:cubism-5.3.03-project-workspace.json:cubismVersion}",
        "cubism-5.3.03-project-workspace.json",
        "${record:cubism-5.3.03-project-workspace.json:sha256}",
        "${record:cubism-5.3.03-project-workspace.json:verificationId}",
        "${record:cubism-5.3.03-project-workspace.json:adapterSliceId}",
        "${record:cubism-5.3.03-project-workspace.json:profileId}"
    );
    private static final Candidate C_UI_BOUNDING_BOX_OVERLAY_5_2_03 = new Candidate(
        "ui-bounding-box-overlay",
        "${record:cubism-5.2.03-ui-bounding-box-overlay.json:cubismVersion}",
        "cubism-5.2.03-ui-bounding-box-overlay.json",
        "${record:cubism-5.2.03-ui-bounding-box-overlay.json:sha256}",
        "${record:cubism-5.2.03-ui-bounding-box-overlay.json:verificationId}",
        "${record:cubism-5.2.03-ui-bounding-box-overlay.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-bounding-box-overlay.json:profileId}"
    );
    private static final Candidate C_UI_BOUNDING_BOX_OVERLAY_5_3_02 = new Candidate(
        "ui-bounding-box-overlay",
        "${record:cubism-5.3.02-ui-bounding-box-overlay.json:cubismVersion}",
        "cubism-5.3.02-ui-bounding-box-overlay.json",
        "${record:cubism-5.3.02-ui-bounding-box-overlay.json:sha256}",
        "${record:cubism-5.3.02-ui-bounding-box-overlay.json:verificationId}",
        "${record:cubism-5.3.02-ui-bounding-box-overlay.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-bounding-box-overlay.json:profileId}"
    );
    private static final Candidate C_UI_BOUNDING_BOX_OVERLAY_5_3_03 = new Candidate(
        "ui-bounding-box-overlay",
        "${record:cubism-5.3.03-ui-bounding-box-overlay.json:cubismVersion}",
        "cubism-5.3.03-ui-bounding-box-overlay.json",
        "${record:cubism-5.3.03-ui-bounding-box-overlay.json:sha256}",
        "${record:cubism-5.3.03-ui-bounding-box-overlay.json:verificationId}",
        "${record:cubism-5.3.03-ui-bounding-box-overlay.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-bounding-box-overlay.json:profileId}"
    );
    private static final Candidate C_UI_CONTROL_APPEARANCE_5_2_03 = new Candidate(
        "ui-control-appearance",
        "${record:cubism-5.2.03-ui-control-appearance.json:cubismVersion}",
        "cubism-5.2.03-ui-control-appearance.json",
        "${record:cubism-5.2.03-ui-control-appearance.json:sha256}",
        "${record:cubism-5.2.03-ui-control-appearance.json:verificationId}",
        "${record:cubism-5.2.03-ui-control-appearance.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-control-appearance.json:profileId}"
    );
    private static final Candidate C_UI_CONTROL_APPEARANCE_5_3_02 = new Candidate(
        "ui-control-appearance",
        "${record:cubism-5.3.02-ui-control-appearance.json:cubismVersion}",
        "cubism-5.3.02-ui-control-appearance.json",
        "${record:cubism-5.3.02-ui-control-appearance.json:sha256}",
        "${record:cubism-5.3.02-ui-control-appearance.json:verificationId}",
        "${record:cubism-5.3.02-ui-control-appearance.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-control-appearance.json:profileId}"
    );
    private static final Candidate C_UI_CONTROL_APPEARANCE_5_3_03 = new Candidate(
        "ui-control-appearance",
        "${record:cubism-5.3.03-ui-control-appearance.json:cubismVersion}",
        "cubism-5.3.03-ui-control-appearance.json",
        "${record:cubism-5.3.03-ui-control-appearance.json:sha256}",
        "${record:cubism-5.3.03-ui-control-appearance.json:verificationId}",
        "${record:cubism-5.3.03-ui-control-appearance.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-control-appearance.json:profileId}"
    );
    private static final Candidate C_UI_EMBEDDED_PANEL_5_2_03 = new Candidate(
        "ui-embedded-panel",
        "${record:cubism-5.2.03-ui-embedded-panel.json:cubismVersion}",
        "cubism-5.2.03-ui-embedded-panel.json",
        "${record:cubism-5.2.03-ui-embedded-panel.json:sha256}",
        "${record:cubism-5.2.03-ui-embedded-panel.json:verificationId}",
        "${record:cubism-5.2.03-ui-embedded-panel.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-embedded-panel.json:profileId}"
    );
    private static final Candidate C_UI_EMBEDDED_PANEL_5_3_02 = new Candidate(
        "ui-embedded-panel",
        "${record:cubism-5.3.02-ui-embedded-panel.json:cubismVersion}",
        "cubism-5.3.02-ui-embedded-panel.json",
        "${record:cubism-5.3.02-ui-embedded-panel.json:sha256}",
        "${record:cubism-5.3.02-ui-embedded-panel.json:verificationId}",
        "${record:cubism-5.3.02-ui-embedded-panel.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-embedded-panel.json:profileId}"
    );
    private static final Candidate C_UI_EMBEDDED_PANEL_5_3_03 = new Candidate(
        "ui-embedded-panel",
        "${record:cubism-5.3.03-ui-embedded-panel.json:cubismVersion}",
        "cubism-5.3.03-ui-embedded-panel.json",
        "${record:cubism-5.3.03-ui-embedded-panel.json:sha256}",
        "${record:cubism-5.3.03-ui-embedded-panel.json:verificationId}",
        "${record:cubism-5.3.03-ui-embedded-panel.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-embedded-panel.json:profileId}"
    );
    private static final Candidate C_UI_MAIN_TOOLBAR_5_2_03 = new Candidate(
        "ui-main-toolbar",
        "${record:cubism-5.2.03-ui-main-toolbar.json:cubismVersion}",
        "cubism-5.2.03-ui-main-toolbar.json",
        "${record:cubism-5.2.03-ui-main-toolbar.json:sha256}",
        "${record:cubism-5.2.03-ui-main-toolbar.json:verificationId}",
        "${record:cubism-5.2.03-ui-main-toolbar.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-main-toolbar.json:profileId}"
    );
    private static final Candidate C_UI_MAIN_TOOLBAR_5_3_02 = new Candidate(
        "ui-main-toolbar",
        "${record:cubism-5.3.02-ui-main-toolbar.json:cubismVersion}",
        "cubism-5.3.02-ui-main-toolbar.json",
        "${record:cubism-5.3.02-ui-main-toolbar.json:sha256}",
        "${record:cubism-5.3.02-ui-main-toolbar.json:verificationId}",
        "${record:cubism-5.3.02-ui-main-toolbar.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-main-toolbar.json:profileId}"
    );
    private static final Candidate C_UI_MAIN_TOOLBAR_5_3_03 = new Candidate(
        "ui-main-toolbar",
        "${record:cubism-5.3.03-ui-main-toolbar.json:cubismVersion}",
        "cubism-5.3.03-ui-main-toolbar.json",
        "${record:cubism-5.3.03-ui-main-toolbar.json:sha256}",
        "${record:cubism-5.3.03-ui-main-toolbar.json:verificationId}",
        "${record:cubism-5.3.03-ui-main-toolbar.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-main-toolbar.json:profileId}"
    );
    private static final Candidate C_UI_STATUS_BAR_5_2_03 = new Candidate(
        "ui-status-bar",
        "${record:cubism-5.2.03-ui-status-bar.json:cubismVersion}",
        "cubism-5.2.03-ui-status-bar.json",
        "${record:cubism-5.2.03-ui-status-bar.json:sha256}",
        "${record:cubism-5.2.03-ui-status-bar.json:verificationId}",
        "${record:cubism-5.2.03-ui-status-bar.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-status-bar.json:profileId}"
    );
    private static final Candidate C_UI_STATUS_BAR_5_3_02 = new Candidate(
        "ui-status-bar",
        "${record:cubism-5.3.02-ui-status-bar.json:cubismVersion}",
        "cubism-5.3.02-ui-status-bar.json",
        "${record:cubism-5.3.02-ui-status-bar.json:sha256}",
        "${record:cubism-5.3.02-ui-status-bar.json:verificationId}",
        "${record:cubism-5.3.02-ui-status-bar.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-status-bar.json:profileId}"
    );
    private static final Candidate C_UI_STATUS_BAR_5_3_03 = new Candidate(
        "ui-status-bar",
        "${record:cubism-5.3.03-ui-status-bar.json:cubismVersion}",
        "cubism-5.3.03-ui-status-bar.json",
        "${record:cubism-5.3.03-ui-status-bar.json:sha256}",
        "${record:cubism-5.3.03-ui-status-bar.json:verificationId}",
        "${record:cubism-5.3.03-ui-status-bar.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-status-bar.json:profileId}"
    );
    private static final Candidate C_UI_TOP_MENU_5_2_03 = new Candidate(
        "ui-top-menu",
        "${record:cubism-5.2.03-ui-top-menu.json:cubismVersion}",
        "cubism-5.2.03-ui-top-menu.json",
        "${record:cubism-5.2.03-ui-top-menu.json:sha256}",
        "${record:cubism-5.2.03-ui-top-menu.json:verificationId}",
        "${record:cubism-5.2.03-ui-top-menu.json:adapterSliceId}",
        "${record:cubism-5.2.03-ui-top-menu.json:profileId}"
    );
    private static final Candidate C_UI_TOP_MENU_5_3_02 = new Candidate(
        "ui-top-menu",
        "${record:cubism-5.3.02-ui-top-menu.json:cubismVersion}",
        "cubism-5.3.02-ui-top-menu.json",
        "${record:cubism-5.3.02-ui-top-menu.json:sha256}",
        "${record:cubism-5.3.02-ui-top-menu.json:verificationId}",
        "${record:cubism-5.3.02-ui-top-menu.json:adapterSliceId}",
        "${record:cubism-5.3.02-ui-top-menu.json:profileId}"
    );
    private static final Candidate C_UI_TOP_MENU_5_3_03 = new Candidate(
        "ui-top-menu",
        "${record:cubism-5.3.03-ui-top-menu.json:cubismVersion}",
        "cubism-5.3.03-ui-top-menu.json",
        "${record:cubism-5.3.03-ui-top-menu.json:sha256}",
        "${record:cubism-5.3.03-ui-top-menu.json:verificationId}",
        "${record:cubism-5.3.03-ui-top-menu.json:adapterSliceId}",
        "${record:cubism-5.3.03-ui-top-menu.json:profileId}"
    );
    private static final Candidate C_WORKSPACE_CONTROL_5_2_03 = new Candidate(
        "workspace-control",
        "${record:cubism-5.2.03-workspace-control.json:cubismVersion}",
        "cubism-5.2.03-workspace-control.json",
        "${record:cubism-5.2.03-workspace-control.json:sha256}",
        "${record:cubism-5.2.03-workspace-control.json:verificationId}",
        "${record:cubism-5.2.03-workspace-control.json:adapterSliceId}",
        "${record:cubism-5.2.03-workspace-control.json:profileId}"
    );
    private static final Candidate C_WORKSPACE_CONTROL_5_3_02 = new Candidate(
        "workspace-control",
        "${record:cubism-5.3.02-workspace-control.json:cubismVersion}",
        "cubism-5.3.02-workspace-control.json",
        "${record:cubism-5.3.02-workspace-control.json:sha256}",
        "${record:cubism-5.3.02-workspace-control.json:verificationId}",
        "${record:cubism-5.3.02-workspace-control.json:adapterSliceId}",
        "${record:cubism-5.3.02-workspace-control.json:profileId}"
    );
    private static final Candidate C_WORKSPACE_CONTROL_5_3_03 = new Candidate(
        "workspace-control",
        "${record:cubism-5.3.03-workspace-control.json:cubismVersion}",
        "cubism-5.3.03-workspace-control.json",
        "${record:cubism-5.3.03-workspace-control.json:sha256}",
        "${record:cubism-5.3.03-workspace-control.json:verificationId}",
        "${record:cubism-5.3.03-workspace-control.json:adapterSliceId}",
        "${record:cubism-5.3.03-workspace-control.json:profileId}"
    );

    private static final Candidate[] CANDIDATES_AUTOBACKUP = {
        C_AUTOBACKUP_5_2_03,
        C_AUTOBACKUP_5_3_02,
        C_AUTOBACKUP_5_3_03
    };
    private static final Candidate[] CANDIDATES_CLIPMASK = {
        C_CLIPMASK_5_2_03,
        C_CLIPMASK_5_3_02,
        C_CLIPMASK_5_3_03
    };
    private static final Candidate[] CANDIDATES_CORE_MODEL_READ = {
        C_CORE_MODEL_READ_5_2_03,
        C_CORE_MODEL_READ_5_3_02
    };
    private static final Candidate[] CANDIDATES_EDITOR_MODEL = {
        C_EDITOR_MODEL_5_2_03,
        C_EDITOR_MODEL_5_3_02,
        C_EDITOR_MODEL_5_3_03
    };
    private static final Candidate[] CANDIDATES_PERFORMANCE_RENDER_SCENE = {
        C_PERFORMANCE_RENDER_SCENE_5_2_03,
        C_PERFORMANCE_RENDER_SCENE_5_3_02,
        C_PERFORMANCE_RENDER_SCENE_5_3_03
    };
    private static final Candidate[] CANDIDATES_PROJECT_WORKSPACE = {
        C_PROJECT_WORKSPACE_5_2_03,
        C_PROJECT_WORKSPACE_5_3_02,
        C_PROJECT_WORKSPACE_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_BOUNDING_BOX_OVERLAY = {
        C_UI_BOUNDING_BOX_OVERLAY_5_2_03,
        C_UI_BOUNDING_BOX_OVERLAY_5_3_02,
        C_UI_BOUNDING_BOX_OVERLAY_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_CONTROL_APPEARANCE = {
        C_UI_CONTROL_APPEARANCE_5_2_03,
        C_UI_CONTROL_APPEARANCE_5_3_02,
        C_UI_CONTROL_APPEARANCE_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_EMBEDDED_PANEL = {
        C_UI_EMBEDDED_PANEL_5_2_03,
        C_UI_EMBEDDED_PANEL_5_3_02,
        C_UI_EMBEDDED_PANEL_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_MAIN_TOOLBAR = {
        C_UI_MAIN_TOOLBAR_5_2_03,
        C_UI_MAIN_TOOLBAR_5_3_02,
        C_UI_MAIN_TOOLBAR_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_STATUS_BAR = {
        C_UI_STATUS_BAR_5_2_03,
        C_UI_STATUS_BAR_5_3_02,
        C_UI_STATUS_BAR_5_3_03
    };
    private static final Candidate[] CANDIDATES_UI_TOP_MENU = {
        C_UI_TOP_MENU_5_2_03,
        C_UI_TOP_MENU_5_3_02,
        C_UI_TOP_MENU_5_3_03
    };
    private static final Candidate[] CANDIDATES_WORKSPACE_CONTROL = {
        C_WORKSPACE_CONTROL_5_2_03,
        C_WORKSPACE_CONTROL_5_3_02,
        C_WORKSPACE_CONTROL_5_3_03
    };

    private static final Map<String, Candidate[]> BY_SLICE = buildIndex();

    private CubismSliceCatalog() {
    }

    private static Map<String, Candidate[]> buildIndex() {
        final Map<String, Candidate[]> index = new LinkedHashMap<>();
        index.put("autobackup", CANDIDATES_AUTOBACKUP);
        index.put("clipmask", CANDIDATES_CLIPMASK);
        index.put("core-model-read", CANDIDATES_CORE_MODEL_READ);
        index.put("editor-model", CANDIDATES_EDITOR_MODEL);
        index.put("performance-render-scene", CANDIDATES_PERFORMANCE_RENDER_SCENE);
        index.put("project-workspace", CANDIDATES_PROJECT_WORKSPACE);
        index.put("ui-bounding-box-overlay", CANDIDATES_UI_BOUNDING_BOX_OVERLAY);
        index.put("ui-control-appearance", CANDIDATES_UI_CONTROL_APPEARANCE);
        index.put("ui-embedded-panel", CANDIDATES_UI_EMBEDDED_PANEL);
        index.put("ui-main-toolbar", CANDIDATES_UI_MAIN_TOOLBAR);
        index.put("ui-status-bar", CANDIDATES_UI_STATUS_BAR);
        index.put("ui-top-menu", CANDIDATES_UI_TOP_MENU);
        index.put("workspace-control", CANDIDATES_WORKSPACE_CONTROL);
        return Map.copyOf(index);
    }

    /**
     * Slices the catalog declares, in deterministic declaration order.
     *
     * @return immutable slice-id list
     */
    public static List<String> slices() {
        return List.copyOf(BY_SLICE.keySet());
    }

    /**
     * Candidates declared for one slice, ascending reviewed version.
     *
     * @param sliceId the slice key to look up
     * @return immutable candidate list, empty for an unknown slice
     */
    public static List<Candidate> candidates(final String sliceId) {
        final Candidate[] found = BY_SLICE.get(sliceId);
        return found == null ? List.of() : List.of(found);
    }

    /**
     * The shared adapter group a slice belongs to. Slices in one group bind a
     * single reviewed generation; a group whose admitted slices resolve to
     * different source versions is rejected rather than mixed.
     *
     * @param sliceId the slice key to look up
     * @return the group name, or the slice id itself for ungrouped slices
     */
    public static String groupOf(final String sliceId) {
        return switch (sliceId) {
                case "ui-bounding-box-overlay", "ui-control-appearance", "ui-embedded-panel", "ui-main-toolbar", "ui-status-bar", "ui-top-menu" -> "chrome";
                case "core-model-read" -> "core";
                case "clipmask", "editor-model", "project-workspace", "workspace-control" -> "document";
                case "autobackup" -> "lifecycle";
                case "performance-render-scene" -> "performance";
            default -> sliceId;
        };
    }

    /**
     * How one named hook contract is verified for compatibility admission.
     */
    public enum HookContractKind {
        /**
         * Selectors permit an installation attempt on any matched generation.
         * The runtime installer must prove an actual target transformation before
         * plugins load, and revoke the dependent capabilities if that proof fails.
         */
        TRANSFORMED_TARGET,
        /**
         * Runtime-installed hook (edit dispatch, physics editor, injected UI,
         * lifecycle bridges). Its contract is satisfied when the slice bound
         * the host's declared reviewed generation: the declared identity pins
         * the generation and every selector in that generation's record was
         * verified against the artifact, so the hook's selector tuple is the
         * reviewed one for this host.
         */
        DECLARED_GENERATION,
        /**
         * Premain native-code patch whose installer digest-matches the loaded
         * artifact's code source. Nothing weaker than the reviewed artifact
         * itself satisfies it — repacked archives never qualify.
         */
        ARTIFACT_DIGEST
    }

    /**
     * Named hook contracts a capability may require in its record
     * {@code capabilityConditions}. The mapping from capability id to hook id
     * lives in each verification record so support policy is versioned with
     * the evidence instead of being a global rule.
     */
    private static final Map<String, HookContractKind> HOOK_CONTRACTS = Map.ofEntries(
        Map.entry("control-appearance", HookContractKind.DECLARED_GENERATION),
        Map.entry("edit-api-dispatch", HookContractKind.TRANSFORMED_TARGET),
        Map.entry("edit-toggle", HookContractKind.DECLARED_GENERATION),
        Map.entry("editor-ui", HookContractKind.DECLARED_GENERATION),
        Map.entry("native-edit-begin", HookContractKind.TRANSFORMED_TARGET),
        Map.entry("mesh-tool-session", HookContractKind.TRANSFORMED_TARGET),
        Map.entry("object-context-menu", HookContractKind.DECLARED_GENERATION),
        Map.entry("performance-fps", HookContractKind.DECLARED_GENERATION),
        Map.entry("physics-editor", HookContractKind.DECLARED_GENERATION),
        Map.entry("texture-atlas", HookContractKind.DECLARED_GENERATION),
        Map.entry("warp-alt-mirror", HookContractKind.TRANSFORMED_TARGET),
        Map.entry("workspace-control", HookContractKind.DECLARED_GENERATION)
    );

    /**
     * The verification kind of one named hook contract.
     *
     * @param hookId the hook contract id from a record's capability condition
     * @return the contract kind, empty for an undeclared hook id
     */
    public static Optional<HookContractKind> hookContract(final String hookId) {
        return Optional.ofNullable(HOOK_CONTRACTS.get(hookId));
    }
}
