package dev.turboism.sdk.storage;

public enum StorageErrorCode {
    INVALID_PATH,
    PERMISSION_DENIED,
    NOT_FOUND,
    ALREADY_EXISTS,
    TYPE_MISMATCH,
    SIZE_LIMIT_EXCEEDED,
    QUOTA_EXCEEDED,
    LINK_ESCAPE,
    ATOMIC_REPLACE_UNAVAILABLE,
    CROSS_ROOT_ATOMIC_MOVE_UNSUPPORTED,
    PARTIAL_DELETE,
    CONFLICT,
    CANCELED,
    RUNTIME_UNAVAILABLE,
    IO_FAILURE
}
