package dev.turboism.adapter.cubism.performance;

/**
 * The static entry points that instrumented Cubism methods call.
 *
 * <p>These run inline on the Cubism render thread, inside bytecode woven into host
 * methods, so they must never propagate a failure into host code: every throwable is
 * swallowed and turned into a recorder failure that also stops the capture. The
 * signatures are referenced by the generated bytecode and cannot change independently
 * of {@code PerformanceProbeMethodTransformer}. Not instantiable.</p>
 */
public final class NativePerformanceProbeBridge {

    private NativePerformanceProbeBridge() { }

    /**
     * Called at the top of an instrumented host method.
     *
     * @param recorder the recorder collecting this capture
     * @param metricId ordinal of the {@link PerformanceProbeMetric} being entered
     * @return the opaque token to hand back to {@link #exit}; {@code 0} when the probe
     *     is not capturing, this call was not sampled, or the enter failed
     */
    public static long enter(final PerformanceProbeRecorder recorder, final int metricId) {
        try {
            return recorder.enter(PerformanceProbeMetric.byId(metricId));
        } catch (Throwable ignored) {
            recorder.fail();
            return 0L;
        }
    }

    /**
     * Called on every exit path of an instrumented host method, normal or exceptional.
     *
     * @param recorder     the recorder collecting this capture
     * @param metricId     ordinal of the {@link PerformanceProbeMetric} being left
     * @param startedNanos the token returned by the matching {@link #enter} call
     */
    public static void exit(
        final PerformanceProbeRecorder recorder,
        final int metricId,
        final long startedNanos
    ) {
        try {
            recorder.exit(PerformanceProbeMetric.byId(metricId), startedNanos);
        } catch (Throwable ignored) {
            recorder.fail();
        }
    }
}
