package dev.turboism.adapter.cubism.mesh;

import java.util.LinkedHashMap;
import java.util.Map;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * ASM-generated stand-ins for the reviewed host triangulation classes.
 *
 * <p>The fixture reproduces the exact instruction shapes the patcher gates on — the same field
 * name, the same method names/descriptors, the {@code aload_1; ldc ""; checkNotNullParameter}
 * prologue, one {@code LinkedHashSet} mutation call site per mutator, and the scanning body of
 * {@code a(j)} — without carrying any official byte. Semantics are faithful: triangle equality is
 * coordinate-based (the index is ignored), the triangle hash is the official constant zero, and
 * the edge query matches undirected endpoint-index pairs on all three sides.</p>
 */
final class TriangulationEdgeIndexFixture implements Opcodes {

    static final String PACKAGE = "com/live2d/graphics3d/editableMesh/triangulation";
    static final String LIST = PACKAGE + "/TriangleList";
    static final String EDGE = PACKAGE + "/j";
    static final String TRIANGLE = PACKAGE + "/l";
    static final String POINT = PACKAGE + "/TriPoint";
    static final String POINT_DESC = "L" + POINT + ";";
    static final String INTRINSICS = "kotlin/jvm/internal/Intrinsics";

    private TriangulationEdgeIndexFixture() {}

    /** Fixture classes contain branches; frame computation never loads host classes. */
    private static ClassWriter fixtureWriter() {
        return new ClassWriter(ClassWriter.COMPUTE_FRAMES) {
            @Override
            protected String getCommonSuperClass(final String a, final String b) {
                return "java/lang/Object";
            }
        };
    }

    /** Binary-name → bytes for every class the fixture needs at runtime. */
    static Map<String, byte[]> classes() {
        final Map<String, byte[]> map = new LinkedHashMap<>();
        map.put(POINT.replace('/', '.'), pointBytes());
        map.put(EDGE.replace('/', '.'), edgeBytes());
        map.put(TRIANGLE.replace('/', '.'), triangleBytes());
        map.put(LIST.replace('/', '.'), listBytes());
        map.put(INTRINSICS.replace('/', '.'), intrinsicsBytes());
        return map;
    }

    /** The reviewed {@code TriangleList} shape, as generated bytecode. */
    static byte[] listBytes() {
        final ClassWriter writer = fixtureWriter();
        writer.visit(V17, ACC_PUBLIC | ACC_FINAL, LIST, null, "java/lang/Object", null);
        writer.visitField(ACC_PRIVATE | ACC_FINAL, "b", "Ljava/util/LinkedHashSet;", null, null)
                .visitEnd();

        final MethodVisitor ctor = writer.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitTypeInsn(NEW, "java/util/LinkedHashSet");
        ctor.visitInsn(DUP);
        ctor.visitMethodInsn(INVOKESPECIAL, "java/util/LinkedHashSet", "<init>", "()V", false);
        ctor.visitFieldInsn(PUTFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        ctor.visitInsn(RETURN);
        ctor.visitMaxs(3, 1);
        ctor.visitEnd();

        // boolean a(l): prologue + b.add(l)
        final MethodVisitor add = writer.visitMethod(
                ACC_PUBLIC, "a", "(L" + TRIANGLE + ";)Z", null, null);
        add.visitCode();
        prologue(add);
        add.visitVarInsn(ALOAD, 0);
        add.visitFieldInsn(GETFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        add.visitVarInsn(ALOAD, 1);
        add.visitMethodInsn(
                INVOKEVIRTUAL, "java/util/LinkedHashSet", "add", "(Ljava/lang/Object;)Z", false);
        add.visitInsn(IRETURN);
        add.visitMaxs(2, 2);
        add.visitEnd();

        // boolean b(l): prologue + b.remove(l)
        final MethodVisitor remove = writer.visitMethod(
                ACC_PUBLIC, "b", "(L" + TRIANGLE + ";)Z", null, null);
        remove.visitCode();
        prologue(remove);
        remove.visitVarInsn(ALOAD, 0);
        remove.visitFieldInsn(GETFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        remove.visitVarInsn(ALOAD, 1);
        remove.visitMethodInsn(
                INVOKEVIRTUAL, "java/util/LinkedHashSet", "remove", "(Ljava/lang/Object;)Z", false);
        remove.visitInsn(IRETURN);
        remove.visitMaxs(2, 2);
        remove.visitEnd();

        // boolean c(l): prologue + b.contains(l)
        final MethodVisitor contains = writer.visitMethod(
                ACC_PUBLIC, "c", "(L" + TRIANGLE + ";)Z", null, null);
        contains.visitCode();
        prologue(contains);
        contains.visitVarInsn(ALOAD, 0);
        contains.visitFieldInsn(GETFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        contains.visitVarInsn(ALOAD, 1);
        contains.visitMethodInsn(
                INVOKEVIRTUAL, "java/util/LinkedHashSet", "contains", "(Ljava/lang/Object;)Z", false);
        contains.visitInsn(IRETURN);
        contains.visitMaxs(2, 2);
        contains.visitEnd();

        // void c(): b.clear()
        final MethodVisitor clear = writer.visitMethod(ACC_PUBLIC, "c", "()V", null, null);
        clear.visitCode();
        clear.visitVarInsn(ALOAD, 0);
        clear.visitFieldInsn(GETFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        clear.visitMethodInsn(INVOKEVIRTUAL, "java/util/LinkedHashSet", "clear", "()V", false);
        clear.visitInsn(RETURN);
        clear.visitMaxs(1, 1);
        clear.visitEnd();

        // List a(j): prologue + insertion-ordered scan collecting triangles where l.b(j)
        final MethodVisitor query = writer.visitMethod(
                ACC_PUBLIC, "a", "(L" + EDGE + ";)Ljava/util/List;", null, null);
        query.visitCode();
        prologue(query);
        query.visitTypeInsn(NEW, "java/util/ArrayList");
        query.visitInsn(DUP);
        query.visitMethodInsn(INVOKESPECIAL, "java/util/ArrayList", "<init>", "()V", false);
        query.visitVarInsn(ASTORE, 2);
        query.visitVarInsn(ALOAD, 0);
        query.visitFieldInsn(GETFIELD, LIST, "b", "Ljava/util/LinkedHashSet;");
        query.visitMethodInsn(
                INVOKEVIRTUAL, "java/util/LinkedHashSet", "iterator", "()Ljava/util/Iterator;", false);
        query.visitVarInsn(ASTORE, 3);
        final Label loop = new Label();
        final Label done = new Label();
        query.visitLabel(loop);
        query.visitVarInsn(ALOAD, 3);
        query.visitMethodInsn(
                INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
        query.visitJumpInsn(IFEQ, done);
        query.visitVarInsn(ALOAD, 3);
        query.visitMethodInsn(
                INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
        query.visitTypeInsn(CHECKCAST, TRIANGLE);
        query.visitVarInsn(ASTORE, 4);
        query.visitVarInsn(ALOAD, 4);
        query.visitVarInsn(ALOAD, 1);
        query.visitMethodInsn(INVOKEVIRTUAL, TRIANGLE, "b", "(L" + EDGE + ";)Z", false);
        query.visitJumpInsn(IFEQ, loop);
        query.visitVarInsn(ALOAD, 2);
        query.visitVarInsn(ALOAD, 4);
        query.visitMethodInsn(
                INVOKEVIRTUAL, "java/util/ArrayList", "add", "(Ljava/lang/Object;)Z", false);
        query.visitInsn(POP);
        query.visitJumpInsn(GOTO, loop);
        query.visitLabel(done);
        query.visitVarInsn(ALOAD, 2);
        query.visitInsn(ARETURN);
        query.visitMaxs(2, 5);
        query.visitEnd();

        writer.visitEnd();
        return writer.toByteArray();
    }

    /** The triangle class: three endpoint fields, undirected-pair edge test, constant hash. */
    private static byte[] triangleBytes() {
        final ClassWriter writer = fixtureWriter();
        writer.visit(V17, ACC_PUBLIC | ACC_FINAL, TRIANGLE, null, "java/lang/Object", null);
        for (final String field : new String[] {"a", "b", "c"}) {
            writer.visitField(ACC_PRIVATE | ACC_FINAL, field, POINT_DESC, null, null).visitEnd();
        }
        constructor(writer, TRIANGLE, "(" + POINT_DESC + POINT_DESC + POINT_DESC + ")V",
                new String[] {"a", "b", "c"});
        for (final String[] getter : new String[][] {{"a", "a"}, {"b", "b"}, {"c", "c"}}) {
            getter(writer, TRIANGLE, getter[0], getter[1]);
        }

        // boolean b(j): (ia==ja&&ib==jb)||(ia==jb&&ib==ja) for edges ab, bc, ca
        final MethodVisitor matches = writer.visitMethod(
                ACC_PUBLIC, "b", "(L" + EDGE + ";)Z", null, null);
        matches.visitCode();
        for (int vertex = 0; vertex < 3; vertex++) {
            emitEndpointIndex(matches, 0, new String[] {"a", "b", "c"}[vertex]);
            matches.visitVarInsn(ISTORE, 2 + vertex); // locals 2..4 = ia, ib, ic
        }
        for (final String getter : new String[] {"a", "b"}) {
            matches.visitVarInsn(ALOAD, 1);
            matches.visitMethodInsn(INVOKEVIRTUAL, EDGE, getter, "()" + POINT_DESC, false);
            matches.visitMethodInsn(INVOKEVIRTUAL, POINT, "getIndex", "()I", false);
            matches.visitVarInsn(ISTORE, getter.equals("a") ? 5 : 6); // locals 5,6 = ja, jb
        }
        pairCheck(matches, 2, 3); // edge a-b
        pairCheck(matches, 3, 4); // edge b-c
        pairCheck(matches, 4, 2); // edge c-a
        matches.visitInsn(ICONST_0);
        matches.visitInsn(IRETURN);
        matches.visitMaxs(2, 7);
        matches.visitEnd();

        // equals: instanceof l && a.equals(o.a) && b.equals(o.b) && c.equals(o.c)
        final MethodVisitor equals = writer.visitMethod(
                ACC_PUBLIC, "equals", "(Ljava/lang/Object;)Z", null, null);
        equals.visitCode();
        equals.visitVarInsn(ALOAD, 1);
        equals.visitTypeInsn(INSTANCEOF, TRIANGLE);
        final Label notTriangle = new Label();
        equals.visitJumpInsn(IFEQ, notTriangle);
        equals.visitVarInsn(ALOAD, 1);
        equals.visitTypeInsn(CHECKCAST, TRIANGLE);
        equals.visitVarInsn(ASTORE, 2);
        for (final String field : new String[] {"a", "b", "c"}) {
            equals.visitVarInsn(ALOAD, 0);
            equals.visitFieldInsn(GETFIELD, TRIANGLE, field, POINT_DESC);
            equals.visitVarInsn(ALOAD, 2);
            equals.visitFieldInsn(GETFIELD, TRIANGLE, field, POINT_DESC);
            equals.visitMethodInsn(
                    INVOKEVIRTUAL, POINT, "equals", "(Ljava/lang/Object;)Z", false);
            equals.visitJumpInsn(IFEQ, notTriangle);
        }
        equals.visitInsn(ICONST_1);
        equals.visitInsn(IRETURN);
        equals.visitLabel(notTriangle);
        equals.visitInsn(ICONST_0);
        equals.visitInsn(IRETURN);
        equals.visitMaxs(2, 3);
        equals.visitEnd();

        // hashCode: the reviewed constant zero
        final MethodVisitor hash = writer.visitMethod(ACC_PUBLIC, "hashCode", "()I", null, null);
        hash.visitCode();
        hash.visitInsn(ICONST_0);
        hash.visitInsn(IRETURN);
        hash.visitMaxs(1, 1);
        hash.visitEnd();

        writer.visitEnd();
        return writer.toByteArray();
    }

    /** Emits {@code this.<field>.getIndex()} leaving the int on the stack. */
    private static void emitEndpointIndex(
            final MethodVisitor mv, final int self, final String field) {
        mv.visitVarInsn(ALOAD, self);
        mv.visitFieldInsn(GETFIELD, TRIANGLE, field, POINT_DESC);
        mv.visitMethodInsn(INVOKEVIRTUAL, POINT, "getIndex", "()I", false);
    }

    /**
     * Emits {@code if ((l[va]==ja && l[vb]==jb) || (l[va]==jb && l[vb]==ja)) return true}.
     * Locals 5/6 hold ja/jb; on a miss control falls through to the next check.
     */
    private static void pairCheck(
            final MethodVisitor mv, final int firstLocal, final int secondLocal) {
        final Label reversed = new Label();
        final Label miss = new Label();
        mv.visitVarInsn(ILOAD, firstLocal);
        mv.visitVarInsn(ILOAD, 5);
        mv.visitJumpInsn(IF_ICMPNE, reversed);
        mv.visitVarInsn(ILOAD, secondLocal);
        mv.visitVarInsn(ILOAD, 6);
        mv.visitJumpInsn(IF_ICMPNE, reversed);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(reversed);
        mv.visitVarInsn(ILOAD, firstLocal);
        mv.visitVarInsn(ILOAD, 6);
        mv.visitJumpInsn(IF_ICMPNE, miss);
        mv.visitVarInsn(ILOAD, secondLocal);
        mv.visitVarInsn(ILOAD, 5);
        mv.visitJumpInsn(IF_ICMPNE, miss);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(miss);
    }

    /** The edge class: two endpoint fields with getters a()/b(). */
    private static byte[] edgeBytes() {
        final ClassWriter writer = fixtureWriter();
        writer.visit(V17, ACC_PUBLIC | ACC_FINAL, EDGE, null, "java/lang/Object", null);
        for (final String field : new String[] {"a", "b"}) {
            writer.visitField(ACC_PRIVATE | ACC_FINAL, field, POINT_DESC, null, null).visitEnd();
        }
        constructor(writer, EDGE, "(" + POINT_DESC + POINT_DESC + ")V", new String[] {"a", "b"});
        for (final String getter : new String[] {"a", "b"}) {
            getter(writer, EDGE, getter, getter);
        }
        writer.visitEnd();
        return writer.toByteArray();
    }

    /** TriPoint: x/y floats plus the index that equality ignores. */
    private static byte[] pointBytes() {
        final ClassWriter writer = fixtureWriter();
        writer.visit(V17, ACC_PUBLIC | ACC_FINAL, POINT, null, "java/lang/Object", null);
        writer.visitField(ACC_PRIVATE | ACC_FINAL, "x", "F", null, null).visitEnd();
        writer.visitField(ACC_PRIVATE | ACC_FINAL, "y", "F", null, null).visitEnd();
        writer.visitField(ACC_PRIVATE | ACC_FINAL, "index", "I", null, null).visitEnd();

        final MethodVisitor ctor = writer.visitMethod(ACC_PUBLIC, "<init>", "(FFI)V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitVarInsn(FLOAD, 1);
        ctor.visitFieldInsn(PUTFIELD, POINT, "x", "F");
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitVarInsn(FLOAD, 2);
        ctor.visitFieldInsn(PUTFIELD, POINT, "y", "F");
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitVarInsn(ILOAD, 3);
        ctor.visitFieldInsn(PUTFIELD, POINT, "index", "I");
        ctor.visitInsn(RETURN);
        ctor.visitMaxs(2, 4);
        ctor.visitEnd();

        for (final String[] accessor :
                new String[][] {{"getX", "x", "F"}, {"getY", "y", "F"}, {"getIndex", "index", "I"}}) {
            final MethodVisitor method = writer.visitMethod(
                    ACC_PUBLIC, accessor[0], "()" + accessor[2], null, null);
            method.visitCode();
            method.visitVarInsn(ALOAD, 0);
            method.visitFieldInsn(GETFIELD, POINT, accessor[1], accessor[2]);
            method.visitInsn(accessor[2].equals("F") ? FRETURN : IRETURN);
            method.visitMaxs(1, 1);
            method.visitEnd();
        }

        // equals: coordinates only — the index is deliberately ignored, like the official class
        final MethodVisitor equals = writer.visitMethod(
                ACC_PUBLIC, "equals", "(Ljava/lang/Object;)Z", null, null);
        equals.visitCode();
        equals.visitVarInsn(ALOAD, 1);
        equals.visitTypeInsn(INSTANCEOF, POINT);
        final Label miss = new Label();
        equals.visitJumpInsn(IFEQ, miss);
        equals.visitVarInsn(ALOAD, 1);
        equals.visitTypeInsn(CHECKCAST, POINT);
        equals.visitVarInsn(ASTORE, 2);
        for (final String field : new String[] {"x", "y"}) {
            equals.visitVarInsn(ALOAD, 0);
            equals.visitFieldInsn(GETFIELD, POINT, field, "F");
            equals.visitVarInsn(ALOAD, 2);
            equals.visitFieldInsn(GETFIELD, POINT, field, "F");
            equals.visitInsn(FCMPL);
            equals.visitJumpInsn(IFNE, miss);
        }
        equals.visitInsn(ICONST_1);
        equals.visitInsn(IRETURN);
        equals.visitLabel(miss);
        equals.visitInsn(ICONST_0);
        equals.visitInsn(IRETURN);
        equals.visitMaxs(2, 3);
        equals.visitEnd();

        final MethodVisitor hash = writer.visitMethod(ACC_PUBLIC, "hashCode", "()I", null, null);
        hash.visitCode();
        hash.visitVarInsn(ALOAD, 0);
        hash.visitFieldInsn(GETFIELD, POINT, "x", "F");
        hash.visitMethodInsn(INVOKESTATIC, "java/lang/Float", "hashCode", "(F)I", false);
        hash.visitInsn(IRETURN);
        hash.visitMaxs(1, 1);
        hash.visitEnd();

        writer.visitEnd();
        return writer.toByteArray();
    }

    /** The Kotlin prologue target; the fixture never depends on the real kotlin-stdlib. */
    private static byte[] intrinsicsBytes() {
        final ClassWriter writer = fixtureWriter();
        writer.visit(V1_8, ACC_PUBLIC | ACC_FINAL, INTRINSICS, null, "java/lang/Object", null);
        final MethodVisitor check = writer.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "checkNotNullParameter",
                "(Ljava/lang/Object;Ljava/lang/String;)V",
                null,
                null);
        check.visitCode();
        check.visitInsn(RETURN);
        check.visitMaxs(0, 2);
        check.visitEnd();
        writer.visitEnd();
        return writer.toByteArray();
    }

    /** {@code aload_1; ldc ""; Intrinsics.checkNotNullParameter} — the reviewed prologue. */
    private static void prologue(final MethodVisitor mv) {
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("");
        mv.visitMethodInsn(
                INVOKESTATIC,
                INTRINSICS,
                "checkNotNullParameter",
                "(Ljava/lang/Object;Ljava/lang/String;)V",
                false);
    }

    /** Three-field constructor assigning each parameter to its field. */
    private static void constructor(
            final ClassWriter writer, final String owner, final String desc, final String[] fields) {
        final MethodVisitor ctor = writer.visitMethod(ACC_PUBLIC, "<init>", desc, null, null);
        ctor.visitCode();
        ctor.visitVarInsn(ALOAD, 0);
        ctor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        for (int index = 0; index < fields.length; index++) {
            ctor.visitVarInsn(ALOAD, 0);
            ctor.visitVarInsn(ALOAD, index + 1);
            ctor.visitFieldInsn(PUTFIELD, owner, fields[index], POINT_DESC);
        }
        ctor.visitInsn(RETURN);
        ctor.visitMaxs(2, fields.length + 1);
        ctor.visitEnd();
    }

    /** Public getter returning a same-named point field. */
    private static void getter(
            final ClassWriter writer, final String owner, final String name, final String field) {
        final MethodVisitor method =
                writer.visitMethod(ACC_PUBLIC, name, "()" + POINT_DESC, null, null);
        method.visitCode();
        method.visitVarInsn(ALOAD, 0);
        method.visitFieldInsn(GETFIELD, owner, field, POINT_DESC);
        method.visitInsn(ARETURN);
        method.visitMaxs(1, 1);
        method.visitEnd();
    }
}
